server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pixelspriter
    username: postgres
    password: root

  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

  web:
    resources:
      static-locations: classpath:/images